Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;

namespace SportsStore.Components
{
	public class CartSummaryViewComponent : ViewComponent
	{
		private Cart cart;
		public CartSummaryViewComponent(Cart cartService)
		{
			cart = cartService;
		}
		public IViewComponentResult Invoke()
		{
			return View(cart);
		}
	}
}

Components/NavigationMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;

namespace SportsStore.Components
{
	public class NavigationMenuViewComponent : ViewComponent
	{
		private IProductRepository repository;
		public NavigationMenuViewComponent(IProductRepository repo)
		{
			repository = repo;
		}
		public IViewComponentResult Invoke()
		{
			ViewBag.SelectedCategory = HttpContext.Request.Query["category"];

			return View(repository.Products
			.Select(x => x.Category)
			.Distinct()
			.OrderBy(x => x));
		}
	}
}

Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using NuGet.Protocol.Core.Types;
using SportsStore.Extensions;
using SportsStore.Models;
using SportsStore.Models.ViewModels;
using System.ComponentModel.DataAnnotations;

namespace SportsStore.Controllers
{
	public class CartController : Controller
	{
		private IProductRepository _productRepository;
		private Cart cart;
		public CartController(IProductRepository productRepository, Cart cartService)
		{
			_productRepository = productRepository;
			this.cart = cartService;			
		}

		public ViewResult Index(string returnUrl) {
			return View(new CartIndexViewModel
			{
				Cart = cart,
				ReturnUrl = returnUrl
			});
		}
		public RedirectToActionResult AddToCart(int productId, string returnUrl)
		{
			Product product = _productRepository.Products.FirstOrDefault(p => p.ProductID== productId);
			if (product is not null)
			{				
				cart.AddItem(product, 1);				
			}

			return RedirectToAction("Index", new { returnUrl });
		}
		public RedirectToActionResult RemoveFromCart(int productId, string returnUrl)
		{
			Product product = _productRepository.Products.FirstOrDefault(p => p.ProductID == productId);

			if (product is not null)
			{			
				cart.RemoveLine(product);				
			}
			return RedirectToAction("Index", new {returnUrl});	
		}
	}
}

Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<link rel="stylesheet" asp-href-include="/bootstrap/css/*.min.css" />
	<title>@ViewBag.Title</title>
	<style>
		.input-validationn-error {
			border-color: red;
			background-color: #fee;
		}
	</style>
	<script src="jquery/jquery.min.js"></script>
	<script src="jquery-validation/jquery.validate.min.js"></script>
	<script src="jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
</head>
<body class="m-1 p-1">
	<div class="bg-info p-2 row">
		<div class="col">
			<h4>@ViewBag.Title</h4>
		</div>
		<div class="col-2">
			<a class="btn btn-primary" asp-action="Logout" asp-controller="Account">Wyloguj</a>
		</div>
	</div>
	@if (TempData["message"] is not null)
	{
		<div class="alert alert-success mt-1">@TempData["message"]</div>
	}
	@RenderBody()
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
	<title>SportsStore</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Bootstrap demo</title>
	<link rel="stylesheet" asp-href-include="/font-awesome/css/*.css" />
	<link rel="stylesheet" asp-href-include="/bootstrap/css/*.min.css" />
</head>
<body>
	<div class="navbar navbar-dark bg-dark" role="navigation">
		<div class="row">
			<a class="col navbar-expand" href="#">Sklep sportowy</a>
			<div class="col-4 text-right">
				@await Component.InvokeAsync("CartSummary")
			</div>
		</div>
	</div>
	<div class="row m-1 p-1">
		<div id="categories" class="col-3">
			@await Component.InvokeAsync("NavigationMenu")
		</div>
		<div class="col-9">
			@RenderBody()
		</div>
	</div>
</body>
</html>

Views/Shared/_ProductSummary.cshtml
@model Product
<div class="card card-outline-primary m-1 p-1">
	<div class="bg-faded p-1">
		<h4>

			@Model.Name
			<span class="badge badge-pill badge-primary" style="float:right">
				<small>@Model.Price.ToString("c")</small>
			</span>
		</h4>
	</div>
	<form id="@Model.ProductID" asp-action="AddToCart" asp-controller="Cart" method="post">
		<input type="hidden" asp-for="ProductID" />
		<input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
		<span class="card-text p-1">
			@Model.Description
			<button type="submit" class="btn-success btn-sm pull-right" style="float:right">
				Dodaj do koszyka
			</button>
		</span>
	</form>
</div>